### PR TITLE
try to allow multiple oracle accounts. 🔮🔮🔮

### PR DESCRIPTION
**Pull request by intmainreturn00**
```
near create-account swt06.intmainreturn0.testnet --masterAccount intmainreturn0.testnet --initialBalance 50
near call intmainreturn0.testnet storage_deposit '' --accountId swt06.intmainreturn0.testnet --amount 49
near deploy --accountId=swt06.intmainreturn0.testnet --wasmFile=target/wasm32-unknown-unknown/release/swt.wasm --initArgs '{"oracles_vec": ["intmainreturn0.testnet", "poddubny.testnet", "swt06.intmainreturn0.testnet"]}' --initFunction new
https://explorer.testnet.near.org/transactions/99XuXf8DoReSfuS11s3W1GD6546f4Yg1vAYNWdhkqxN7

### mint from swt06.intmainreturn0.testnet oracle
near call swt06.intmainreturn0.testnet record '{"account_id":"intmainreturn0.testnet", "steps": 10000}' --accountId swt06.intmainreturn0.testnet --gas=300000000000000
https://explorer.testnet.near.org/transactions/5wQXrKmxCytMgnc9dPkujgm67PbgvcCQCq7fU3chbyw4

### mint from intmainreturn0.testnet oracle
near call swt06.intmainreturn0.testnet record '{"account_id":"intmainreturn0.testnet", "steps": 10000}' --accountId intmainreturn0.testnet --gas=300000000000000
https://explorer.testnet.near.org/transactions/Gnk5cy8DLBifAgho63ZC33NYK8uBVHwfP3AEe8msyWpR

### mint from poddubny.testnet oracle
near call swt06.intmainreturn0.testnet record '{"account_id":"intmainreturn0.testnet", "steps": 10000}' --accountId poddubny.testnet --gas=300000000000000

```

### CODE REVIEW

**Comment by poddubnyoleg** [comment]
start getting logs on each mint in batch (e.g. https://explorer.testnet.near.org/transactions/D3duVxWA51XBRD5ewgijnLGV2evD6FfmG41LQeCLxyi8)
>  Log [swt06.intmainreturn0.testnet]: poddubny.testnet

when sending batch with >100 mints get logging error 

> type: 'FunctionCallError',
>   context: undefined,
>   index: 0,
>   kind: { ExecutionError: 'The number of logs will exceed the limit 100' },

**Comment by poddubnyoleg** [comment]
token has no decimals 

> poddubny$ near call swt06.intmainreturn0.testnet ft_balance_of '{"account_id":"poddubny.testnet"}' --accountId poddubny.testnet
> Scheduling a call: swt06.intmainreturn0.testnet.ft_balance_of({"account_id":"poddubny.testnet"})
> Doing account.functionCall()
> Transaction Id 97LdfirLm1ie7TU62gVPxUotdCFq8iRdcA8QxCxEuQuA
> To see the transaction in the transaction explorer, please open this url in your browser
> https://explorer.testnet.near.org/transactions/97LdfirLm1ie7TU62gVPxUotdCFq8iRdcA8QxCxEuQuA
> '4279'

**Comment by poddubnyoleg** [comment]
formula seems to decline very fast, need to check if there are enough decimals in k stored

**Comment by poddubnyoleg** [comment]
full list of oracle ids for testing 
['f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92', 'b18c66baba05d37dceaeaba743ca20b7ca077ff51861d69484939f80', 'poddubny.testnet', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db9206', '0952227bc4149978a3e57bbae26e9ae8c0d7d9e0fb267a2a179cafb2', '2b16781c2e614e0e48fba532d591e3d293cb3cf6bbb601a8a1a2e9bd', '16b5d44ce3e24652291bedefc484b2ae9f414c41963b54556b013aa5', 'dev-1638368516362-28263900316041', 'e09644746eebdd4752a17bed1d632c395720f65a46e31d1d260e77a5', '1fbbd38dca41fdcfe06dc41bec0a86fa7b67f4f8695f292b07664062', 'e7c81b495a2e703507823169346f55c76681c887937b9d5ff2b70577', '9e1a12ca8cd0d161a5f097d3e8b279f4e9389a1d7a48491f3475c97e', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db', '7decdbd0b274350167ac652f0d71d8ce9bfaefb696b37aa0d3b1c1db', '9cf22fcf8c9046c336a3403671e77847754146aad0d9912ffb473bdf', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db920', '3a84d3213a3d0926b65b85af424fa4142e03da79059af6037fec449b', '3b0018b793b4f5c3e9d6d900d5a9c7ba6038713969e003b617f8a9fc', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2', '0020bb98eb586c398de2ec9f3bc4a09e2b31df164ab539b2065c8701', '128aef0eaab32bd9431599ce63f60ff76e4aaecd646c41fe6520a477', 'e449e2c812e69a7344131f0674828220af3d10569a9d5b6abdfb3916', 'beaa2b7330beeb2d18d405acbabfbb408a011e773c45a3022be5e018', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7', '65fb16895c3c0ececdffddc548789011b84d6dd478c39d8b5ba44151', 'ff38c7d3fef553aa9cd50b35d1550e91264577d104619f9ff9f15607', 'a24e1910e6e1fc9ebffb78694c8c1c159bc5979dce5a27b9e781d1ad', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7d', '4c7144edfe88c29fa298af4117026e0378e4deb81e748ade553e3ff5', 'a5710943f4cda2dbb215935fa803972c629347f0997645c56a6af404', '852946492b191edde85a0348bbc665689da474b4d6419eff11842d18', '341c0902001dcfd3e1ee47acd738fe5192b5f13e5bb8f1dc9ce8e9cd', 'c5d06d38e8b1f89e57c2263d870c1fa968111d62e692eb510b0f636d', 'f892bc646afb7f4b6bee1466b897a12c83fa32c2b3777d343c23c95a', 'e03889a45805090915a40ce26c3e0148aa5072d13c13cadabc4007f4', 'ec3733e268dc0508f04cc0ed2d0379ef2e54f960ad3197bea7dbf68b', '8ec0225375bed1f41f9116ea7e304ff7c08974d6705097a7cc52c3a9', 'f0f096baf3f4729f579ac4f9a48ab3102b82ba3fa71d5c3b37d1f36b', 'eb86b72885c9fd20844c3498063733a447bfc02ec7c7572b5075433b', '074b17cdd47b780198245c5da9a91d87e8e45c4c47be54d8623a5afc', 'a9e0ed8d3154c0d7ebc686b847f442b0fb03bff0d67da7d5c6506be9', '7511e77a778a2dcfb906b3a358037eb317db86e21171849f49fa0ab2', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e', 'c6d751c80ce523ab23e2bff7c679d31e927cd9f98a5b2c6103673c39', 'b1911f3458a0f73a25ff2f511a4522f8fd57c1b2e06e17de57c9bd59', '30a73e6dc1cb90d9d7a073a89ae80c4e9dc4e830ec65700a245bbd37', '369638ca693f8c17e33e5c5d379b08c01e52b5f99b4c14cb34404eee', '33fd8265a5861195c870b74d71a81d3df92389852bbf5a6bab37fa21', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db9', '801961e195e5159a0aae400f764469adb2f570609e84d915c4b34fd7', '6535a3d2f90d1bfb96c9e74783ce03a3bc1e6767c624ba44e3f7308d', 'afcacb56c6d356ad4e3a04de364f5f85199118bff8373747a8b66f48', '6e5ca052ced8c49da1c084ef72afc1db7c778d57c0dfe5a5bf755278', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2a1', 'f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2a', '3c2cf2a96f7d142533f2fc3d92b01d01c7e9ede24520eb45b289c4f7', '4e7186dbe9ac6d138a437a770c54ff709d3dab3e679296be02aef718', '320f7e178eedc903bdddc68727b8c2447df509d06204b4951f3ffb47', '9c0877a138f5308a6909b5101d9e6bd2fabd36bf0f69d221ffd546fa', '568a60e9f7b6783c2955ecc46264be6381d9e5619f12575bd0a772d5', '76470137d8d81e4455bfa0fc5cc23f14953b380d2c5fd3ec3efddfe8', 'bbab974b6bffc7532696e9f2c67da10d6626461533181fb731d7bd1a']

**Comment by intmainreturn00** [comment]
@poddubnyoleg try swt07.intmainreturn00.testnet 🙌
```
near create-account swt07.intmainreturn00.testnet --masterAccount intmainreturn00.testnet --initialBalance 50


near deploy --accountId=swt07.intmainreturn00.testnet --wasmFile=target/wasm32-unknown-unknown/release/swt.wasm --initArgs '{"oracles_vec": ["intmainreturn0.testnet", "swt07.intmainreturn00.testnet", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92", "b18c66baba05d37dceaeaba743ca20b7ca077ff51861d69484939f80", "poddubny.testnet", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db9206", "0952227bc4149978a3e57bbae26e9ae8c0d7d9e0fb267a2a179cafb2", "2b16781c2e614e0e48fba532d591e3d293cb3cf6bbb601a8a1a2e9bd", "16b5d44ce3e24652291bedefc484b2ae9f414c41963b54556b013aa5", "dev-1638368516362-28263900316041", "e09644746eebdd4752a17bed1d632c395720f65a46e31d1d260e77a5", "1fbbd38dca41fdcfe06dc41bec0a86fa7b67f4f8695f292b07664062", "e7c81b495a2e703507823169346f55c76681c887937b9d5ff2b70577", "9e1a12ca8cd0d161a5f097d3e8b279f4e9389a1d7a48491f3475c97e", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db", "7decdbd0b274350167ac652f0d71d8ce9bfaefb696b37aa0d3b1c1db", "9cf22fcf8c9046c336a3403671e77847754146aad0d9912ffb473bdf", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db920", "3a84d3213a3d0926b65b85af424fa4142e03da79059af6037fec449b", "3b0018b793b4f5c3e9d6d900d5a9c7ba6038713969e003b617f8a9fc", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2", "0020bb98eb586c398de2ec9f3bc4a09e2b31df164ab539b2065c8701", "128aef0eaab32bd9431599ce63f60ff76e4aaecd646c41fe6520a477", "e449e2c812e69a7344131f0674828220af3d10569a9d5b6abdfb3916", "beaa2b7330beeb2d18d405acbabfbb408a011e773c45a3022be5e018", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7", "65fb16895c3c0ececdffddc548789011b84d6dd478c39d8b5ba44151", "ff38c7d3fef553aa9cd50b35d1550e91264577d104619f9ff9f15607", "a24e1910e6e1fc9ebffb78694c8c1c159bc5979dce5a27b9e781d1ad", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7d", "4c7144edfe88c29fa298af4117026e0378e4deb81e748ade553e3ff5", "a5710943f4cda2dbb215935fa803972c629347f0997645c56a6af404", "852946492b191edde85a0348bbc665689da474b4d6419eff11842d18", "341c0902001dcfd3e1ee47acd738fe5192b5f13e5bb8f1dc9ce8e9cd", "c5d06d38e8b1f89e57c2263d870c1fa968111d62e692eb510b0f636d", "f892bc646afb7f4b6bee1466b897a12c83fa32c2b3777d343c23c95a", "e03889a45805090915a40ce26c3e0148aa5072d13c13cadabc4007f4", "ec3733e268dc0508f04cc0ed2d0379ef2e54f960ad3197bea7dbf68b", "8ec0225375bed1f41f9116ea7e304ff7c08974d6705097a7cc52c3a9", "f0f096baf3f4729f579ac4f9a48ab3102b82ba3fa71d5c3b37d1f36b", "eb86b72885c9fd20844c3498063733a447bfc02ec7c7572b5075433b", "074b17cdd47b780198245c5da9a91d87e8e45c4c47be54d8623a5afc", "a9e0ed8d3154c0d7ebc686b847f442b0fb03bff0d67da7d5c6506be9", "7511e77a778a2dcfb906b3a358037eb317db86e21171849f49fa0ab2", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e", "c6d751c80ce523ab23e2bff7c679d31e927cd9f98a5b2c6103673c39", "b1911f3458a0f73a25ff2f511a4522f8fd57c1b2e06e17de57c9bd59", "30a73e6dc1cb90d9d7a073a89ae80c4e9dc4e830ec65700a245bbd37", "369638ca693f8c17e33e5c5d379b08c01e52b5f99b4c14cb34404eee", "33fd8265a5861195c870b74d71a81d3df92389852bbf5a6bab37fa21", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db9", "801961e195e5159a0aae400f764469adb2f570609e84d915c4b34fd7", "6535a3d2f90d1bfb96c9e74783ce03a3bc1e6767c624ba44e3f7308d", "afcacb56c6d356ad4e3a04de364f5f85199118bff8373747a8b66f48", "6e5ca052ced8c49da1c084ef72afc1db7c778d57c0dfe5a5bf755278", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2a1", "f86edd60952fee3ed6413a2a95782a49823e24645dce27c08c7db92066e2a", "3c2cf2a96f7d142533f2fc3d92b01d01c7e9ede24520eb45b289c4f7", "4e7186dbe9ac6d138a437a770c54ff709d3dab3e679296be02aef718", "320f7e178eedc903bdddc68727b8c2447df509d06204b4951f3ffb47", "9c0877a138f5308a6909b5101d9e6bd2fabd36bf0f69d221ffd546fa", "568a60e9f7b6783c2955ecc46264be6381d9e5619f12575bd0a772d5", "76470137d8d81e4455bfa0fc5cc23f14953b380d2c5fd3ec3efddfe8", "bbab974b6bffc7532696e9f2c67da10d6626461533181fb731d7bd1a"]}' --initFunction new
https://explorer.testnet.near.org/transactions/4rQgbhHtPoj3TLvao2pkoBdXmrhHzkLsyjRbPrxN1Q1j

### mint from swt07.intmainreturn00.testnet oracle
near call swt07.intmainreturn00.testnet record '{"account_id":"intmainreturn0.testnet", "steps": 10000}' --accountId swt07.intmainreturn00.testnet --gas=300000000000000

near view swt07.intmainreturn00.testnet ft_balance_of '{"account_id":"intmainreturn0.testnet"}'
View call: swt07.intmainreturn00.testnet.ft_balance_of({"account_id":"intmainreturn0.testnet"})
'10000000000000000000'

### mint from intmainreturn0.testnet oracle
near call swt07.intmainreturn00.testnet record '{"account_id":"intmainreturn0.testnet", "steps": 10000}' --accountId intmainreturn0.testnet --gas=300000000000000

near view swt07.intmainreturn00.testnet ft_balance_of '{"account_id":"intmainreturn0.testnet"}'
View call: swt07.intmainreturn00.testnet.ft_balance_of({"account_id":"intmainreturn0.testnet"})
'20000000000000000000'
```

**Pull request merged**
